data:
  clip_duration: 4.0
  dataloader_params:
    batch_size: 4
    num_workers: 8
    pin_memory: true
  sample_rate: 48000
  train_dataset:
    max_samples: 13000
    root_directory: /home/xinlong/MSR/data/train_test
  val_dataset:
    n_per_dt: 10
    root_directory: /home/xinlong/MSR/data/dataForTest
exp_name: melRNN_vocal_restoration
loss:
  reconstruction_loss:
    hop_length:
    - 256
    - 512
    - 128
    n_fft:
    - 1024
    - 2048
    - 512
    n_mels:
    - 80
    - 160
    - 40
    sample_rate: 48000
model:
  name: MelRNN
  params:
    hidden_channels: 128
    hop_size: 512
    num_groups: 4
    num_layers: 4
    sample_rate: 48000
    window_size: 2048
  pretrained_path: /home/xinlong/MSR/pretrain/baseline/pretrain/Vocals.pth
optimizer:
  betas:
  - 0.8
  - 0.99
  lr: 0.0002
project_name: msrkit
trainer:
  devices:
  - 0
  early_stopping_patience: 10
  log_every_n_steps: 50
  max_epochs: 1000
  precision: bf16-mixed
  save_dir: ./runs
